AppStore.UI/Controllers/ManageController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using AppStore.UI.Models;

namespace AppStore.UI.Controllers
{
    [Authorize]
    public class ManageController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ManageController()
        {
        }

        public ManageController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Manage/Index
        public async Task<ActionResult> Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Your two-factor authentication provider has been set."
                : message == ManageMessageId.Error ? "An error has occurred."
                : message == ManageMessageId.AddPhoneSuccess ? "Your phone number was added."
                : message == ManageMessageId.RemovePhoneSuccess ? "Your phone number was removed."
                : "";

            var userId = User.Identity.GetUserId();
            var model = new IndexViewModel
            {
                HasPassword = HasPassword(),
                PhoneNumber = await UserManager.GetPhoneNumberAsync(userId),
                TwoFactor = await UserManager.GetTwoFactorEnabledAsync(userId),
                Logins = await UserManager.GetLoginsAsync(userId),
                BrowserRemembered = await AuthenticationManager.TwoFactorBrowserRememberedAsync(userId)
            };
            return View(model);
        }

        //
        // POST: /Manage/RemoveLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveLogin(string loginProvider, string providerKey)
        {
            ManageMessageId? message;
            var result = await UserManager.RemoveLoginAsync(User.Identity.GetUserId(), new UserLoginInfo(loginProvider, providerKey));
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                message = ManageMessageId.RemoveLoginSuccess;
            }
            else
            {
                message = ManageMessageId.Error;
            }
            return RedirectToAction("ManageLogins", new { Message = message });
        }

        //
        // GET: /Manage/AddPhoneNumber
        public ActionResult AddPhoneNumber()
        {
            return View();
        }

        //
        // POST: /Manage/AddPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddPhoneNumber(AddPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            // Generate the token and send it
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), model.Number);
            if (UserManager.SmsService != null)
            {
                var message = new IdentityMessage
                {
                    Destination = model.Number,
                    Body = "Your security code is: " + code
                };
                await UserManager.SmsService.SendAsync(message);
            }
            return RedirectToAction("VerifyPhoneNumber", new { PhoneNumber = model.Number });
        }

        //
        // POST: /Manage/EnableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), true);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // POST: /Manage/DisableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DisableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), false);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // GET: /Manage/VerifyPhoneNumber
        public async Task<ActionResult> VerifyPhoneNumber(string phoneNumber)
        {
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), phoneNumber);
            // Send an SMS through the SMS provider to verify the phone number
            return phoneNumber == null ? View("Error") : View(new VerifyPhoneNumberViewModel { PhoneNumber = phoneNumber });
        }

        //
        // POST: /Manage/VerifyPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyPhoneNumber(VerifyPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePhoneNumberAsync(User.Identity.GetUserId(), model.PhoneNumber, model.Code);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.AddPhoneSuccess });
            }
            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("", "Failed to verify phone");
            return View(model);
        }

        //
        // GET: /Manage/RemovePhoneNumber
        public async Task<ActionResult> RemovePhoneNumber()
        {
            var result = await UserManager.SetPhoneNumberAsync(User.Identity.GetUserId(), null);
            if (!result.Succeeded)
            {
                return RedirectToAction("Index", new { Message = ManageMessageId.Error });
            }
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", new { Message = ManageMessageId.RemovePhoneSuccess });
        }

        //
        // GET: /Manage/ChangePassword
        public ActionResult ChangePassword()
        {
            return View();
        }

        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.ChangePasswordSuccess });
            }
            AddErrors(result);
            return View(model);
        }

        //
        // GET: /Manage/SetPassword
        public ActionResult SetPassword()
        {
            return View();
        }

        //
        // POST: /Manage/SetPassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetPassword(SetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await UserManager.AddPasswordAsync(User.Identity.GetUserId(), model.NewPassword);
                if (result.Succeeded)
                {
                    var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                    if (user != null)
                    {
                        await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

AppStore.UI/Controllers/ProductController.cs
using AppStore.Common;
using AppStore.Models;
using AppStore.UI.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace AppStore.UI.Controllers
{
    public class ProductController : Controller
    {

        // GET: Product
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Get(int id)
        {
            ShowProductDetiels result = new ShowProductDetiels();

            var product = new Biz.ProductBiz().Get(id);
            result.Product = product;
            double Rate = product.Rate;
            int downloads = new Biz.DownloadBiz().GetDownloadCount(id);
            int comments = new Biz.CommentBiz().CommnetsCount(id);
            result.Comments = new Biz.CommentBiz().Get(id).OrderByDescending(x => x.DateTime).ToList();
            result.Counts = new CountsViewModel() { CommentsCount = comments, DownloadsCount = downloads, RateCounts = Rate };

            return View("SmallProduct", result);
        }

        public ActionResult Search()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Search(string strSearch)
        {
            var list = new Biz.ProductBiz().Find(strSearch);

            return View("list", list);

        }
        public ActionResult Manage()
        {
            return View(GetList());
        }

        public ActionResult List()
        {
            return View(GetList());
        }
        private List<Product> GetList()
        {
            return new Biz.ProductBiz().GetAll();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Product p)
        {
            if (Request.Files.Count > 0)
            {
                p.ProductImages = new List<ProductImage>();
                string pathImage = Server.MapPath("~/Content/images/iconProduct/");
                string pathFile = Server.MapPath("~/Content/Downloads/");
                int counterIamge = 0;
                int counterFile = 0;

                foreach (HttpPostedFileBase file in Request.Files.GetMultiple("FileUpload"))
                {
                    file.SaveAs(pathFile + file.FileName);
                    p.FileUpload = file.FileName;
                    p.FileSize = getFileSize(file.InputStream.Length);
                    counterFile++;
                }

                foreach (HttpPostedFileBase file in Request.Files.GetMultiple("Logo"))
                {
                    string fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    file.SaveAs(pathImage + fileName);

                    p.ProductImages.Add(new ProductImage()
                    {
                        ImageName = fileName,
                        Type = counterIamge == p.LogoIndex ? ImageType.Logo : ImageType.Details
                    });

                    counterIamge++;
                }
            }

            var result = new Biz.ProductBiz().Create(p);

            if (result.Succeed)
                return RedirectToAction("Manage");
            return View(p);
        }

        private string getFileSize(double len)
        {
            string[] sizes = { "B", "KB", "MB", "GB", "TB" };
            int order = 0;
            while (len >= 1024 && order < sizes.Length - 1)
            {
                order++;
                len = len / 1024;
            }

            // Adjust the format string to your preferences. For example "{0:0.#}{1}" would
            // show a single decimal place, and no space.
            return String.Format("{0:0.##}{1}", len, sizes[order]);
        }

        [HttpGet]
        public ActionResult Create()
        {


            ViewBag.Groups = new Biz.GroupBiz().GetAll().Select(x =>
                        new SelectListItem
                        {
                            Value = x.Id.ToString(),
                            Text = x.Name
                        });

            return View(new Product());
        }

        //[HttpPost]
        //public ActionResult Edit(Product p, User u)
        //{
        //    new Biz.ProductBiz().Edit(p, u);
        //    return View();
        //}


        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(Product p, User u)
        {
            new Biz.ProductBiz().Delete(p, u);
            return View();
        }

        [HttpGet]
        public ActionResult Delete()
        {
            return View();
        }
    }
}

AppStore.UI/Controllers/UserDownloadsController.cs
using AppStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppStore.UI.Controllers
{
    public class UserDownloadsController : Controller
    {
        // GET: UserDownloads
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Download(int productId)
        {
            OperationResult result = new Biz.DownloadBiz().Create(new UserDownload() { Product_Id = productId });
            if (result.Succeed)
            {
                string path = AppDomain.CurrentDomain.BaseDirectory + "Content\\Downloads\\";
                string fileName = new Biz.ProductBiz().GetAll().Where(x => x.Id == productId).Select(x => x.FileUpload).FirstOrDefault();
                //TODO : Name File Download
                byte[] fileBytes = System.IO.File.ReadAllBytes(path + fileName);
                return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);

            }
            return File(new byte[0] { }, System.Net.Mime.MediaTypeNames.Application.Octet, "notFound.txt");

        }


        public int CountDownloads(int ProductId)
        {
            return new Biz.DownloadBiz().GetDownloadCount(ProductId);
        }


    }
}

AppStore.UI/Views/Product/Delete.cshtml
@model AppStore.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Developer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Developer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.License)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.License)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppStore.UI/Views/Product/ListProduct.cshtml
@model AppStore.Model.Product

<div class="product-box">
    
</div>

AppStore.UI/Views/Product/SmallProduct.cshtml
@model AppStore.UI.Models.ShowProductDetiels
@using AppStore.Common
<div class="direction-rtl">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-heading">
                <div class="panel-heading bg">
                    <div class="panel-title">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="col-lg-3">
                                    <button type="button" name="mark" class="btn bouton-image mark btn-mark"></button>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <h1 class="glyphicon  text-right text-white m-0 p-0 mt-3">برنامه</h1>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="col-lg-3">
                                <button type="button" class="btn btn-install btn-block">
                                    <h3>نصب</h3>
                                </button>
                            </div>

                        </div>

                        <div class="col-lg-2">
                            <h1 class="product-name"><strong>@Model.Product.Name</strong></h1><h4><small>@Model.Product.Name</small></h4>

                        </div>
                        <div class="col-lg-2">
                            <img class="img-responsive" src="~/Content/images/iconProduct/@(Model.Product.Logo == null ? "default.png" : Model.Product.Logo.ImageName)" width="185" height="185">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-lg-3">

                            <div class="testimonial w-100 h-100  p-3 text-center">
                                <button class="btn bouton-image icondownload"></button>
                                <div class="separator">&nbsp;</div>
                                <h4 class="message text-center text-gray">@Model.Counts.DownloadsCount</h4>
                            </div>
                        </div>
                        <div class="col-lg-3">

                            <div class="testimonial w-100 h-100  p-3 text-center">
                                <button class="btn bouton-image iconSize"></button>
                                <div class="separator">&nbsp;</div>
                                <h4 class="message text-center text-gray">@Model.Counts.CommentsCount</h4>
                            </div>
                        </div>
                        <div class="col-lg-3">

                            <div class="testimonial w-100 h-100  p-3 text-center">
                                <button class="btn bouton-image iconCountComment"></button>
                                <div class="separator">&nbsp;</div>
                                <h4 class="message text-center text-gray">@Model.Counts.RateCounts</h4>
                            </div>
                        </div>
                        <div class="col-lg-3">

                            <div class="testimonial w-100 h-100  p-3 text-center">
                                <button class="btn bouton-image iconShareing"></button>
                                <div class="separator">&nbsp;</div>
                                <h4 class="message text-center text-gray">شبکه های اجتماعی</h4>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-10 col-sm-offset-1" id="logout">

                            <div>

                                <div class="tab-content">
                                    <div class="tab-pane active" id="comments-logout">
                                        <ul class="media-list">
                                            <li class="media">
                                                <div class="media-body ">
                                                    <div class="well well-lg lang-bar ">
                                                        <div class="text-lg-center">
                                                            <img src="~/Content/images/Unlike.jpg" class="disabled list-inline" />
                                                            <img src="~/Content/images/Unlike.jpg" class="disabled list-inline" />
                                                            <img src="~/Content/images/Unlike.jpg" class="disabled list-inline" />
                                                            <img src="~/Content/images/like.jpg" class="disabled list-inline" />
                                                            <img src="~/Content/images/like.jpg" class="disabled list-inline" />
                                                        </div>
                                                        <p class="media-comment  text-lg-center text-capitalize">
                                                            <strong>امتیاز من به این برنامه</strong>
                                                        </p>
                                                    </div>
                                                </div>

                                            </li>
                                            @foreach (var item in Model.Comments)
                                            {
                                                string data = Helper.MeladiToShamsi(item.DateTime.ToShortDateString());
                                                <li class="media">
                                                    <a class="pull-right" href="#">
                                                        <img class="media-object img-circle" src="~/Content/images/Users/User2.jpg" alt="profile">
                                                    </a>
                                                    <div class="media-body">
                                                        <div class="well well-lg" style="position: relative">
                                                            <div class="left-corner"></div>
                                                            <div class="right-corner"></div>
                                                            <div class="text-lg-center">
                                                                @{
                                                                    int countlike = item.UserRate;
                                                                    int countUnlike = 5 - item.UserRate;
                                                                    for (int i = 0; i < countlike; i++)
                                                                    {
                                                                        <button class="btn bouton-image like  list-inline"></button>
                                                                    }

                                                                    for (int i = 0; i < countUnlike; i++)
                                                                    {

                                                                        <button class="btn bouton-image Unlike  list-inline"></button>
                                                                    }
                                                                }
                                                            </div>
                                                            <h4 class="media-heading text-uppercase reviews">
                                                                @item.User.FirstName  @item.User.LastName
                                                            </h4>
                                                            <ul class="media-date text-uppercase reviews list-inline">
                                                                <li class="dd"> @data.Substring(8, 2)</li>
                                                                <li class="mm">@data.Substring(5, 2)</li>
                                                                <li class="aaaa">@data.Substring(0, 4)</li>
                                                            </ul>


                                                            <p class="media-comment">
                                                                @item.Description
                                                            </p>

                                                            <a class="btn btn-info btn-circle text-uppercase" href="#" id="reply"><span class="glyphicon glyphicon-share-alt"></span> پاسخ</a>
                                                        </div>
                                                    </div>
                                                </li>
                                                                    }

                                        </ul>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">

            <div class="well well-lg lang-bar">

                <form class="form-horizontal" id="commentForm" role="form">


                    <div class="form-group">

                        <div class="text-lg-center">
                            <button type="button" name="userRate" class="btn bouton-image Unlike  list-inline rate"></button>
                            <button type="button" name="userRate" class="btn bouton-image Unlike  list-inline rate"></button>
                            <button type="button" name="userRate" class="btn bouton-image Unlike  list-inline rate"></button>
                            <button type="button" name="userRate" class="btn bouton-image Unlike list-inline rate"></button>
                            <button type="button" name="userRate" class="btn bouton-image Unlike list-inline rate"></button>
                            <input type="hidden" id="counterRate" value="0" />
                        </div>
                        <label><span class="text-right"> نظر</span></label>
                        <div class="col-sm-12">


                            <textarea class="form-control comment" name="addComment" id="addComment" rows="5"></textarea>
                            <label class="error text-danger" />
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button class="btn btn-success btn-circle text-uppercase btn-comment" type="submit" id="submitComment"><span class="glyphicon glyphicon-send"></span> ارسال </button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>



    <hr>


</div>



@Scripts.Render("~/bundles/jquery")

<script type="text/javascript">
    $(document).ready(function () {
        var counter = 0;
        $('body').on('click', '.btn-install', function () {
            location = '@Url.Action("Download", "UserDownloads", new { productId = Model.Product.Id })'
        });

        $('body').on('click', '.btn-comment', function (e) {
            e.preventDefault();
            var description = $('.comment').val();
            if(description == "")
            {
                $('.error').html('لطفا کامنت را پر کنید');
            }else{
                $.ajax({
                    dataType: 'json',
                    url: "/Comment/Create",
                    type:'post',
                    data: {description:description,productId:@Model.Product.Id,Rate:$("#counterRate").val()},
                    success:function(data)
                    {
                        if(data.success)
                            window.location.reload();
                        else
                            alert('لطفا مجدد تلاش کنید عملیات ناموفق است');
                    },

                });
            }
            return false;
        });
        $('body').on('click', '.rate', function () {
            if($(this).hasClass("like"))
            {
                $(this).removeClass("like").addClass("Unlike");
                $("#counterRate").val(function(i, val) { return +val-1 });
            }
            else{
                $(this).removeClass("Unlike").addClass("like");
                $("#counterRate").val(function(i, val) { return +val+1 });
            }
        });

        $('body').on('click', '.btn-mark', function (e) {
            e.preventDefault();

            $.ajax({
                dataType: 'json',
                url: "/BookMarks/Create",
                type:'post',
                data: {productId:@Model.Product.Id},
                success:function(data)
                {
                },

            });
            return false;
        });


    });
</script>